name: gemini_interaction
description: A Flutter app to interact with Gemini API
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: any
  file_picker: any
  image_picker: any
  path_provider: any
  permission_handler: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true